identifier: k5t2f0t330adq5oa
allowErrorCollect: false
appPort: 1864
staticPort: 1668
reloadPort: 2667
hostName: localhost
projectName: kernpro
homeFolder: C:\GIT\kernpro
distFolder: dist/kernpro
outDir: C:\GIT\kernpro\dist\static
handle404: ''
